### PR TITLE
Fixes for 404 error and unittestable

### PR DESCRIPTION
**Pull request by jeroendelau**
As per the issue logged

Two issues fixed
1. 404 does not work as advertised.
2. I'm using there4/slim-test-helpers, and this lib is creating some unexpected responses. I narrowed it down to the use of Slim::getInstance(). By passing the $app in the constructor this can be circumvented.

### CODE REVIEW

**Comment by dogancelik** [comment]
Thank you for your work, can you please squash the commits before I merge it?

**Comment by jeroendelau** [comment]
Sorry mate, bit new to git. What do you mean squash commits?

**Comment by dogancelik** [comment]
[Here's a page explaining it](https://git-scm.com/book/tr/v2/Git-Tools-Rewriting-History#Squashing-Commits), it basically means combining commits into one commit.

Also I'm afraid you need to revert your [latest commit](https://github.com/jeroendelau/slim-json/commit/673032cf8919fe34817ff8a2fda1c52193a24105) about CORS because that is not the main issue of this pull request.

**Comment by dogancelik** [comment]
I'm working on this and will accept your commits except CORS behaviour commit.
I will merge and close this in few hours.

**Pull request closed without merging**
